version: '2'
services:
  app1:
    image: testapp
    environment:
      NODE_ENV: test
      MONGODB_URI: mongodb://mongo/testapp
    ports:
      - 10000:9002
    links:
     - mongo
    depends_on:
     - mongo

  app2:
    image: prodapp
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo/prodapp
    ports:
      - 10001:8080
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - ./data/db
      - ./data/configdb

volumes:
  mongo-data:
  mongo-config:
